displayName: Badger- Reworked
type: middleware
iconPath: .assets/icon.png

import: github.com/hhftechnology/badger

summary: Middleware auth bouncer for Pangolin with x-forwarded support

testData:
    apiBaseUrl: "http://localhost:3001/api/v1"
    userSessionCookieName: "p_session_token"
    resourceSessionRequestParam: "p_session_request"
